spring:
  application:
    name: lottoApi
#  datasource:
#    url: jdbc:h2:~/lotto
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

#logging:
#  level:
#    root: debug
#    com.donggoos: debug
server:
  port: 8888